### ISSUE TITLE
[E::idx_find_and_load] Could not retrieve index file for when running bookend elr

### ISSUE THREAD

**Issue by xiekunwhy** [Gregor-Mendel-Institute/bookend#2]
Hi,

Bookend User Guide, told me that bookend elr need a name-sorted bam, but when I run bookend elr, \[E::idx_find_and_load\] Could not retrieve index file for my bam file.

How to index name-sorted bam file?

Best,
Kun

**Comment by maschon0** [comment]
Hello @xiekunwhy,
This IO Error is output by the package ['pysam'](https://pysam.readthedocs.io/en/latest/api.html) when it cannot find a BAM index file. Because name-sorted files cannot be indexed, it is expected that Bookend runs on a BAM file without an index, so this error message does not change the tools performance. I updated the Bookend 'dev' branch to suppress these error messages. If you would like to work with the latest development build, you can uninstall the pip package, then:
```
git clone https://github.com/Gregor-Mendel-Institute/bookend  
cd bookend  
git checkout dev  
python setup.py install --user  
```
